#!/usr/bin/env php
<?php
require_once 'libraries';

function isLtInstalled(\includes\SQL $db) : bool
{
    $sql = "SHOW TABLES LIKE 'conges_config'";
    $res = $db->query($sql);
    return $res->num_rows == 1;
}

function getInstanceName(\includes\SQL $db) : string
{
    $sql="SELECT conf_valeur FROM conges_config WHERE conf_nom='URL_ACCUEIL_CONGES' ";
    $ret = $db->query($sql);
    $res = $ret->fetch_array();
    return $res['conf_valeur'];
}

function isApiJoignable(\includes\SQL $db) : bool
{
    $apiUrl = getInstanceName($db) . '/api/hello_world';
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Content-Type: application/json',
        'Accept: application/json'
    ));
    curl_setopt($ch, CURLOPT_URL,$apiUrl);
    $result = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return 200 === $code;
}

function isApiConfigSecure(\includes\SQL $db) : bool
{
    $configUrl = getInstanceName($db) . '/vendor/libertempo/api/configuration.json';
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_URL,$configUrl);
    $result = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    return 200 != $code;
}

// test curl
if (!extension_loaded('curl')) {
    displayError('L\'extension cURL pour php (php-curl) n\'est pas installée');
}

// test cfg/env.php
if (!file_exists(CONFIG_PATH . 'env.php')) {
    displayError(CONFIG_PATH . 'env.php n\'existe pas ou est inaccessible');
}

// test cfg/dbconnect.php
if (!file_exists(CONFIG_PATH . 'dbconnect.php')) {
    displayError(CONFIG_PATH . 'dbconnect.php n\'existe pas ou est inaccessible');
}
require_once CONFIG_PATH . 'dbconnect.php';

// test php-mysql
if (!function_exists('mysqli_connect')) {
    displayError('L\'extension mysqli pour php (php-mysql) n\'est pas activée');
}

// test bdd access
try {
    \includes\SQL::singletonWithoutDb();
}
catch (Exception $e) {
    display($e->getMessage());
    displayError('Accès à mysql/mariadb impossible.');
}

// test bdd exist
if (!\includes\SQL::existsDatabase($mysql_database)) {
    displayInfo('La base de données n\'existe pas. Elle sera créée lors de l\'installation');
    display('Vérifications effectuées avec succès.');
    exit();
}

$db = \includes\SQL::singleton();

//test table
if (!isLtInstalled($db)) {
    displayError('La base de données semble vide, une réinstallation est nécessaire.');
}

// test vendor/libertempo/api/configuration.json
if (!file_exists(API_SYSPATH . 'configuration.json')) {
    displayError(API_SYSPATH . 'configuration.json n\'existe pas ou est inaccessible');
}

displayInfo('Version actuelle de Libertempo : ' . getInstalledVersion());
displayInfo('Adresse web : ' . getInstanceName($db));

// test http api
if (!isApiJoignable($db)) {
    displayError('L\'API semble inaccessible. Vérifiez la configuration d\'apache.');
}

//test http configuration.json access
if (!isApiConfigSecure($db)) {
    displayError('Le fichier de configuration de l\'api est exposé. Vérifiez la configuration du virtual host.');
}

display('Vérifications effectuées avec succès.');
