#!/usr/bin/env php
<?php
require_once 'libraries';
require_once CONFIG_PATH . 'dbconnect.php';

define('INSTALLATION_PATH', PATCH_PATH . DS . 'Installation' . DS);
define('API_SYSPATH', ROOT_PATH . 'vendor' . DS . 'libertempo' . DS . 'api' . DS);

function destroyDatabase(\includes\SQL $db, string $name) : bool
{
    try {
        $req = 'DROP DATABASE `' . $name . '`';
        $res = $db->query($req);
        return true;
    } catch (\mysqli_sql_exception $e) {
        return false;
    }
}

display('Destruction totale…');
display('Contrôles généraux…');
if (!\includes\SQL::existsDatabase($mysql_database)) {
    displayFail();
}

display('Vous êtes sur le point de supprimer toute la base de données!');
$input = getValue('Êtes-vous sûr (y/N) :');
if ($input != 'y' &&  $input != 'Y') {
    displayError('Destruction annulée.');
}

display('Suppression base de données…');
$db = \includes\SQL::singleton();
if (!destroyDatabase($db, $mysql_database)) {
    displayFail();
}

display('Destruction de la DB effectuée avec succès.');
