#!/usr/bin/env php
<?php
require_once 'libraries';
require_once CONFIG_PATH . 'dbconnect.php';

define('INSTALLATION_PATH', PATCH_PATH . DS . 'Installation' . DS);
define('API_PATH', ROOT_PATH . 'api' . DS);
define('API_SYSPATH', ROOT_PATH . 'vendor' . DS . 'Libertempo' . DS . 'libertempo-api' . DS);

/**
 * Définit un nom pour l'instance. Doit coller à ce que le vhost a déclaré.
 */
function nameInstance(\includes\SQL $db, string $name) : bool
{
    if (!filter_var($name, FILTER_VALIDATE_URL)) {
        return false;
    }

    $req = 'UPDATE `conges_config` SET conf_valeur = "' . $db->quote($name) . '"
    WHERE conf_nom = "URL_ACCUEIL_CONGES" LIMIT 1';
    $db->query($req);

    // @TODO: à supprimer quand la mise à jour des vhosts sera effective
    $path = parse_url($name, \PHP_URL_PATH);
    $contentFile = file_get_contents(API_PATH . '.htaccess.example');
    $newContent = str_replace('vendor', $path . 'vendor', $contentFile);
    return file_put_contents(API_PATH . '.htaccess', $newContent);
}

/**
 * Définit les données de configuration pour l'API
 *
 * @param array $data Données de configuration
 */
function setDataConfigurationApi(string $server, string $base, string $user, string $password) : bool
{
    $data = [
        'db' => [
            'serveur' => $server,
            'base' => $base,
            'utilisateur' => $user,
            'mot_de_passe' => $password,
        ],
    ];

    return file_put_contents(API_SYSPATH . 'configuration.json', json_encode($data));
}

/**
 * Execute le fichier de patch d'installation et retourne sa version
 */
function executePatch() : string
{
    $currentPatch = "0.0";
    foreach (glob(INSTALLATION_PATH . '/*.sql') as $filename) {
        $currentPatch = basename($filename, '.sql');
        // il n'est sensé n'y en avoir qu'un
        execute_sql_file($filename);
        break;
    }

    return $currentPatch;
}

echo 'Installation…', "\n";

// Quelques vérifications de base…
$instanceName = $argv[1] ?? null;
if (null == $instanceName) {
    displayError("Nom d'instance vide");
}

if (0 != getInstalledVersion()) {
    displayError('Application déjà installée');
}

list($major, $minor,) = explode('.', executePatch());
$versionMaj = $major . '.' . $minor;

$db = \includes\SQL::singleton();
if(!setLastMaj($db, $versionMaj)) {
    displayError('Mise à jour du patch échouée');
}

if (!nameInstance($db, $instanceName)) {
    displayError('Nommage de l\'instance impossible');
}

if (!setDataConfigurationApi($mysql_serveur, $mysql_database, $mysql_user, $mysql_pass)) {
    displayError('Configuration de l\'API impossible');
}

$updateLang = "UPDATE conges_config SET conf_valeur = 'fr_FR' WHERE conf_nom = 'lang' LIMIT 1";
$db->query($updateLang);

echo 'Installation terminée avec succès.', "\n";
