#!/usr/bin/env php
<?php
define('DS', DIRECTORY_SEPARATOR);
define('ROOT_PATH', dirname(__FILE__, 3) . DS);
define('PATCH_PATH', ROOT_PATH . 'App' . DS . 'Patchs' . DS);
define('CONFIG_PATH', ROOT_PATH . DS . 'cfg'. DS);
define('DUMP_PATH', ROOT_PATH . 'dump' . DS);
define('PUBLIC_PATH', ROOT_PATH . 'Public' . DS);
define('ASSETS_PATH', PUBLIC_PATH . 'Assets' . DS);
define('IMG_PATH', ASSETS_PATH . 'Img' . DS);
define('_PHP_CONGES', 1);

require_once ROOT_PATH . 'vendor/autoload.php';
require_once ROOT_PATH . 'fonctions_conges.php';
require_once CONFIG_PATH . 'dbconnect.php';

function displayFail()
{
    displayError('Échec');
}

/**
 * Affiche un cas d'erreur et s'arrête
 */
function displayError(string $message)
{
    display($message);
    exit(1);
}

function display(string $message)
{
    echo $message, "\n";
}

function setLastMaj(\includes\SQL $db, string $versionLastMaj) : bool
{
    $req = 'UPDATE `conges_appli` SET appli_valeur = "' . $versionLastMaj . '" WHERE appli_variable = "version_last_maj" LIMIT 1';
    $db->query($req);
    // @TODO: Compat with <1.12 versions
    if ($db->affected_rows > 0) {
        return true;
    }
    return 0 < file_put_contents('/tmp/lt-last-version', $versionLastMaj);
}

function getInstalledVersion() : string
{
    $db = \includes\SQL::singleton();
    try {
        $sql="SELECT conf_valeur FROM conges_config WHERE conf_nom='installed_version' ";
        if ($reglog = $db->query($sql)) {
            if($result=$reglog->fetch_array()) {
                return $result['conf_valeur'];
            }
        }
    } catch (\Exception $e) {
        return 0;
    }
    return 0;
}
