#!/usr/bin/env php
<?php
require_once 'libraries';
require_once ROOT_PATH . 'version.php';
require_once INCLUDE_PATH . 'fonction.php';

display('Sauvegarde…');
if (!\includes\SQL::existsDatabase($mysql_database)) {
    displayError('Application non installée');
}
$installedVersion = getInstalledVersion();
$versionDerniereMAJ = getVersionDerniereMiseAJour(\includes\SQL::singleton(), $installedVersion);

// Quelques vérifications de base…
if ('0.0.0' == $versionDerniereMAJ) {
    displayError('l\'application n\'est pas encore installée.');
}

display('Sauvegarde de la DB courante…');
try {
    sauvegardeAsFile($installedVersion, 'end');
} catch (\Exception $e) {
    displayFail();
}
